version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/cdTest
permissions:
  - object: /home/ec2-user/cdTest
    owner: ec2-user
    group: root
    mode: 755
#배포 시 발생하는 다양한 생멸주기마다 원하는 스크립트를 실행할 수 있게 후크를 제공
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 60
      runas: root